# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f26362a3fc92bd496f3974a9731c5e3a8c99289a5686b7afdf90b4e98f6747d6b475e2040e9b6f1997c07601f0c2d0d64765873436d9cf6368902de3856e50

test:
  secret_key_base: 51b043d97251ac5a547f21e58626b533f7b5f7baec9714f73f9245c0dc6b4378d6265354955bfeb4359ebf246766be5fc6507555e265b4b193188d08478427e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
